FROM koyeb/docker-compose

# Set the working directory inside the container
WORKDIR /app

# Copy everything from the current directory on the host into /motac-apis in the container
COPY . /app

# Run Docker Compose using the compose file in /motac-apis
CMD ["docker-compose", "-f", "/app/docker-compose.yml", "up"]
